# Generated by Django 2.0.2 on 2018-12-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_active',
            field=models.BooleanField(default=True, verbose_name='邮箱验证状态'),
        ),
    ]
